on:
  push:

  # run when starred
  watch:
    types: [started]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - run: dotnet run
      env:
        GITHUB_TOKEN: ${{ secrets.NO_SCOPE_TOKEN }}
